---
# https://github.com/grafana/grafana-ansible-collection/tree/main/roles/promtai√Æ

- name: Install and configure promtail
  ansible.builtin.include_role:
    name: grafana.grafana.promtail
  vars:
    promtail_http_listen_address: "{{ services_ip }}"
    promtail_http_listen_port: 9080
    promtail_clients:
      - url: http://{{ hostvars[groups['MonitoringMaster'][0]].master_ip }}:3100/loki/api/v1/push
    promtail_scrape_configs:
    - job_name: system
      static_configs:
        - targets:
            - localhost
          labels:
            host: "{{ ansible_hostname }}"
            job: varlogs
            __path__: /var/log/*.log
    - job_name: docker_log_scrape
      docker_sd_configs:
        - host: unix:///var/run/docker.sock
          refresh_interval: 10s
      relabel_configs:
        - source_labels: ['__meta_docker_container_name']
          regex: '/(.*)'
          target_label: 'container'
        - source_labels: ['__meta_docker_container_log_stream']
          target_label: 'logstream'
        - source_labels: ['__meta_docker_container_label_logging_jobname']
          target_label: 'job'
