services:

  urbackup-client:
    image: uroni/urbackup-client:latest
    restart: always
    environment:
      - TZ={{ timezone }}
      - URBACKUP_SERVER_NAME={{ urbackup.server_host }}
      - URBACKUP_CLIENT_NAME={{ ansible_hostname }}
      - URBACKUP_CLIENT_AUTHKEY={{ urbackup.authkey }}
    volumes:
      - "{{ docker.docker_dir }}:/backup"
    command:
      - --internet-only
      - -r
      - server-confirms
    ports:
      - "55414:55414"
      - "55415:55415"
      - "35623:35623/udp"
