# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3.json

api:
  dashboard: true
  insecure: false

log:
  level: INFO

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy_network

entryPoints:
  web:
    address: ":80"
  internal:
    address: ":8080"
  websecure:
    address: ":443"
    http:
      tls: 
        certResolver: "{{ docker.cert_resolver }}"
        domains:
          - main: "{{ docker.domain }}"
            sans:
              - "*.{{ docker.domain }}"
  # tailscale:
  #   address: "{{ services_ip }}:8443"
  #   http:
  #     tls: 
  #       certResolver: "{{ docker.cert_resolver }}"
  #       domains:
  #         - main: "{{ docker.domain }}"
  #           sans:
  #             - "*.{{ docker.domain }}"

certificatesResolvers:
  ovh:
    acme:
      email: "{{ email }}"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: ovh
        delayBeforeCheck: "0"
