---
# https://github.com/artis3n/ansible-collection-tailscale/tree/main
- name: Tailscale
  ansible.builtin.include_role:
    name: artis3n.tailscale.machine  
  vars:
    tailscale_authkey: "{{ tailscale.authkey }}"
    tailscale_args: "--ssh"

- name: Set Tailscale IP fact
  ansible.builtin.set_fact:
    tailscale_ip: "{{ tailscale_node_ipv4 | default('N/A') }}"
    