
tailscale_ip: null
services_ip: "{{ tailscale_ip }}"

#######################
# User 
#######################

username: "susu"
email: "seurya2@gmail.com"
sudo_group: "sudo"
ssh_group: "admin"
timezone: "Europe/Brussels"

#######################
# Update Settings
#######################

extra_packages:
  - curl
  - vim
  - htop
  - python3-jsondiff
  - neofetch

allow_reboot: false
reboot_delay: 60 
security_updates_only: true  # For production systems

#######################
# Docker
#######################

prune_containers: false
prune_images: true
prune_volumes: false  # Be careful with volumes!

docker:
  cleanup: true
  docker_dir: "/docker"
  domain: dev.autostack.ovh
  cert_resolver: "ovh"
  docker_networks:
    - proxy_network

#######################
# Monitoring
# https://github.com/geerlingguy/ansible-role-node_exporter/blob/master
#######################

node_exporter_version: 'latest'
loki_uninstall: true
promtail_version: 'latest'

node_exporter_arch: 'amd64'
node_exporter_download_url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz

node_exporter_bin_path: /usr/local/bin/node_exporter

node_exporter_state: started
node_exporter_enabled: true
node_exporter_restart: on-failure

node_exporter_host: "{{ services_ip }}"
node_exporter_port: 9100
node_exporter_options: ''

node_promtail_enabled: true