############
# Proxmox and VM config
############

# Proxmox cluster node name where VMs will be created (e.g., 'pve')
proxmox_node: pve

# Storage name to use for disks and cloud-init (e.g., 'local-lvm')
proxmox_storage: local-lvm

# Bridge to attach VMs to (e.g., 'vmbr0')
proxmox_bridge: vmbr0

# Storage for cloud-init snippets (usually 'local')
proxmox_snippets_storage: local

# Keyboard layout to configure via cloud-init
keyboard_layout: be-latin1

# Ubuntu LTS cloud image URL (24.04 default; change as desired)
ubuntu_lts_image_url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"

# VM definitions
vms:
  - name: demo-vm-1
    vmid: 101
    memory: 2048
    cores: 2
    disk_gb: 20
    ciuser: ubuntu
    ipconfig0: dhcp  # or "ip=192.168.1.50/24,gw=192.168.1.1"

  - name: demo-vm-2
    vmid: 102
    memory: 4096
    cores: 2
    disk_gb: 30
    ciuser: ubuntu
    ipconfig0: dhcp
